name: Update README with prompt.md

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Runs every hour (adjust as needed)

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update README
        run: |
          echo '```markdown' > README.md
          cat prompt.md >> README.md
          echo '```' >> README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update README with latest prompt.md" || echo "No changes to commit"
          git push
